// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CatItemController from "./cat_item_controller"
application.register("cat-item", CatItemController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ListItemController from "./list_item_controller"
application.register("list-item", ListItemController)

import TaskItemController from "./task_item_controller"
application.register("task-item", TaskItemController)
