meta_product_name: "Mind Bubble"
meta_title: "Mind Bubble - The app to help people with ADHD navigate the world"
meta_description: "The app to help adults with or without ADHD navigate the world.
                   Relieve the pain of losing track of time, forgetting useful information and being disorganised.
                   Create a mind map to help with their organisation, to trigger memory and planning ahead."
meta_image: "mind-bubble-png.png"
